version: "3.4"
services:
    nodered:
        image: nodered/node-red
        container_name: recorder-app
        restart: always
        user: '0'
        environment:
          - TZ=Europe/Stockholm
          - SERVER_ADDRESS=rec.juhlin.me
          - MQTT_ADDRESS=mqtt.juhlin.me
          - MQTT_USER=pandos
          - MQTT_PASSWORD=mandos          
          - MINIO_ADDRESS=10.13.8.20
          - MINIO_KEY=u15ZLeACBFPy0KqtxHDN
          - MINIO_SECRET=ISRok8ICxFqkqVBHJ9aoBvhavYJ5gIqWaD1sLFC0
          - ACS_ADDRESS=10.13.8.120
          - ACS_USER=admin
          - ACS_PASSWORD=r00tpa88
        ports:
          - '18000:1880'
        links:
          - influxdb      
        volumes:
          - ./:/data
    influxdb:
        container_name: recorder-influx
        restart: always
        image: influxdb:1.8.10
        user: '0'
        volumes:
          - ./influxdb:/var/lib/influxdb
#        ports:
#          - '8086:8086' 