version: "3.4"
services:
    nodered:
        image: nodered/node-red
        container_name: recorder-app
        restart: always
        user: '0'
        ports:
          - '18100:1880'
        links:
          - influxdb
        volumes:
          - ./:/data
        environment:
#Set you enviroment data here
          - TZ=Europe/Stockholm
          - SERVER_ADDRESS=a.b.c.d:18100
          - MQTT_ADDRESS=a.b.c.d
          - MQTT_USER=MQTT user if needed.  Leave blank if not.
          - MQTT_PASSWORD=MQTT password if needed.  Leave blank if not.
          - AXIS_ROOT_PASSWORD=Devidce root account password
          - MINIO_ADDRESS=a.b.c.d
          - MINIO_PORT=9000
          - MINIO_KEY=Key from generated credentials in minio server
          - MINIO_SECRET=Secret from generated credentials in minio server
          - ACS_ADDRESS=ACS address if available
          - ACS_USER=ACS use if available
          - ACS_PASSWORD=ACS user if available
    influxdb:
        container_name: recorder-influx
        restart: always
        image: influxdb:1.8.10
        user: '0'
        volumes:
          - ./influxdb:/var/lib/influxdb
# Uncomment below if you want to expose the Influx DB
#        ports:
#          - '8086:8086' 
