version: "3.4"
services:
    nodered:
        image: nodered/node-red
        container_name: recorder-app
        restart: always
        user: '0'
        ports:
          - '18100:1880'
        links:
          - influxdb
        volumes:
          - ./:/data
        environment:
#Set you enviroment data here
          - TZ=Europe/Stockholm
          - SERVER_ADDRESS=a.a.a.a:18100
          - MQTT_ADDRESS=b.b.b.b
          - MQTT_USER=some user or leave blank if no user required
          - MQTT_PASSWORD=some password or leave blank if no user required
          - AXIS_ROOT_PASSWORD=root account password to Axis cameras
          - MINIO_ADDRESS=c.c.c.c
          - MINIO_KEY=XXXXXX
          - MINIO_SECRET=CCCCCCC
          - ACS_ADDRESS=ACS address if available
          - ACS_USER=ACS user if available
          - ACS_PASSWORD=ACS password if available
    influxdb:
        container_name: recorder-influx
        restart: always
        image: influxdb:1.8.10
        user: '0'
        volumes:
          - ./influxdb:/var/lib/influxdb
# Uncomment below if you want to expose the Influx DB
#        ports:
#          - '8086:8086' 